#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if is-bool-val-false "${TDM_AUTO_UPDATE:-1}"; then
    echo "true"
elif [ "${TDM_UPDATE_CHECK_INTERVAL:-86400}" -eq 0 ]; then
    echo "true"
else
    echo "false"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
