#!/bin/sh
#
# Periodically install newer Twitch Drops Miner builds published upstream.
#

set -u

DATA_DIR="${TDM_DATA_DIR:-/config/app}"
PID_FILE=/var/run/tdm/app.pid

restart_miner() {
    if [ "${KEEP_APP_RUNNING:-0}" -eq 0 ]; then
        # Stopping the miner would stop the whole container.
        echo "KEEP_APP_RUNNING is disabled, the new build will be used the next"
        echo "time the miner starts."
        return
    fi

    pid="$(cat "${PID_FILE}" 2> /dev/null || true)"

    if [ -z "${pid}" ] || [ ! -d "/proc/${pid}" ]; then
        echo "The miner does not seem to be running, the new build will be used"
        echo "the next time it starts."
        return
    fi

    echo "Restarting the miner to run the new build..."
    kill -TERM "${pid}" 2> /dev/null
}

/opt/tdm/bin/tdm-fetch.sh --dest "${DATA_DIR}"
rc="$?"

case "${rc}" in
    0)
        ;;
    10)
        take-ownership "${DATA_DIR}"
        if is-bool-val-true "${TDM_UPDATE_RESTART:-1}"; then
            restart_miner
        else
            echo "The new build will be used the next time the miner starts."
        fi
        ;;
    *)
        echo "WARNING: could not check for a newer build, will try again later."
        ;;
esac

exit 0

# vim:ft=sh:ts=4:sw=4:et:sts=4
